name: Sync Intel granulate-utils

on:
  schedule:
    - cron: '0 6 * * 1' # Runs Mondays at 6am UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pinterest/granulate-utils
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Add Intel Remote
        run: git remote add intel https://github.com/intel/granulate-utils.git

      - name: Fetch Intel
        run: git fetch intel

      - name: Create or Update sync branch
        run: |
          git checkout -B intel-sync
          git merge --no-ff intel/master || true

      - name: Push sync branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -f origin intel-sync

      - name: Create or Update PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: intel-sync
          title: 'Sync from upstream Intel granulate-utils'
          body: |
            Automated weekly sync from Intel's granulate-utils repository.
          base: master

